// const pattern = {
//     prefix: "pattern-",
//     names: [
//         "checks",
//         "grid",
//         "dots",
//         "cross-dots",
//         "diagonal-lines",
//         "horizontal-lines",
//         "diagonal-stripes",
//         "horizontal-stripes",
//         "vertical-stripes",
//         "triangles",
//         "zigzag"
//     ],
//     sizes: [
//         "sm",
//         "md",
//         "lg",
//         "xl"
//     ]
// }
const ClassNameOfPatterns = [
    "pattern-checks-sm",
    "pattern-checks-md",
    "pattern-checks-lg",
    "pattern-checks-xl",

    "pattern-grid-sm",
    "pattern-grid-md",
    "pattern-grid-lg",
    "pattern-grid-xl",

    "pattern-dots-sm",
    "pattern-dots-md",
    "pattern-dots-lg",
    "pattern-dots-xl",

    "pattern-cross-dots-sm",
    "pattern-cross-dots-md",
    "pattern-cross-dots-lg",
    "pattern-cross-dots-xl",

    "pattern-diagonal-lines-sm",
    "pattern-diagonal-lines-md",
    "pattern-diagonal-lines-lg",
    "pattern-diagonal-lines-xl",

    "pattern-horizontal-lines-sm",
    "pattern-horizontal-lines-md",
    "pattern-horizontal-lines-lg",
    "pattern-horizontal-lines-xl",

    "pattern-vertical-lines-sm",
    "pattern-vertical-lines-md",
    "pattern-vertical-lines-lg",
    "pattern-vertical-lines-xl",

    "pattern-diagonal-stripes-sm",
    "pattern-diagonal-stripes-md",
    "pattern-diagonal-stripes-lg",
    "pattern-diagonal-stripes-xl",

    "pattern-horizontal-stripes-sm",
    "pattern-horizontal-stripes-md",
    "pattern-horizontal-stripes-lg",
    "pattern-horizontal-stripes-xl",

    "pattern-vertical-stripes-sm",
    "pattern-vertical-stripes-md",
    "pattern-vertical-stripes-lg",
    "pattern-vertical-stripes-xl",

    "pattern-triangles-sm",
    "pattern-triangles-md",
    "pattern-triangles-lg",
    "pattern-triangles-xl",

    "pattern-zigzag-sm",
    "pattern-zigzag-md",
    "pattern-zigzag-lg",
    "pattern-zigzag-xl",
]
const pastelColors = [
    { name: "Light Blue", hex: "#edf2fb" },
    { name: "Pale Blue", hex: "#d7e3fc" },
    { name: "Baby Blue", hex: "#ccdbfd" },
    { name: "Sky Blue", hex: "#c1d3fe" },
    { name: "Light Cornflower Blue", hex: "#abc4ff" },
    { name: "Peach", hex: "#ffc09f" },
    { name: "Pale Yellow", hex: "#ffee93" },
    { name: "Ivory", hex: "#fcf5c7" },
    { name: "Pale Turquoise", hex: "#a0ced9" },
    { name: "Mint Green", hex: "#adf7b6" },
    { name: "Periwinkle", hex: "#809bce" },
    { name: "Light Steel Blue", hex: "#79addc" },
    { name: "Peach", hex: "#ffc09f" },
    { name: "Pale Yellow", hex: "#ffee93" },
    { name: "Mint Green", hex: "#adf7b6" },
    { name: "Salmon Pink", hex: "#ff686b" },
    { name: "Cornflower Blue", hex: "#6e78ff" },
    { name: "Coral", hex: "#ff7477" },
    { name: "Lavender", hex: "#dfb2f4" },
    { name: "Turquoise", hex: "#55d6c2" },
    { name: "Light Coral", hex: "#ff9770" },
    { name: "Pastel Pink", hex: "#ffd1dc" },
    { name: "Pastel Orange", hex: "#ffdcb8" },
    { name: "Pastel Yellow", hex: "#ffefaa" },
    { name: "Pastel Green", hex: "#baf6c1" },
    { name: "Pastel Blue", hex: "#aad8e6" },
    { name: "Pastel Purple", hex: "#d9b3e6" },
    { name: "Pastel Lavender", hex: "#e6c9ec" },
    { name: "Pastel Peach", hex: "#ffd8bf" },
    { name: "Pastel Mint", hex: "#b0eacd" },
    { name: "Pastel Coral", hex: "#ffb8a4" },
    { name: "Pastel Gray", hex: "#cfd8dc" },
    { name: "Pastel Lilac", hex: "#e6d7f1" },
    { name: "Pastel Salmon", hex: "#ffc8b2" },
    { name: "Pastel Turquoise", hex: "#a2d7d4" },
    { name: "Pastel Beige", hex: "#f9ead6" },
    { name: "Pastel Apricot", hex: "#ffd8c9" },
    { name: "Pastel Sky Blue", hex: "#b7d6f9" },
    { name: "Pastel Lime", hex: "#d8f3af" },
    { name: "Pastel Orchid", hex: "#e8cff7" },
    { name: "Pastel Teal", hex: "#c7f2e2" },
    { name: "Pastel Rose", hex: "#ffc5ca" }
];
const DaisyuiThemes = [
    "light",
    // "dark",
    "cupcake",
    "bumblebee",
    "emerald",
    "corporate",
    // "synthwave",
    // "retro",
    // "cyberpunk",
    // "valentine",
    // "halloween",
    "garden",
    // "forest",
    // "aqua",
    "lofi",
    "pastel",
    "fantasy",
    "wireframe",
    // "black",
    // "luxury",
    // "dracula",
    "cmyk",
    "autumn",
    // "business",
    "acid",
    "lemonade",
    // "night",
    // "coffee",
    "winter"
]

export {
    ClassNameOfPatterns,
    pastelColors,
    DaisyuiThemes
}